name: Continuous Integration

on:
  push:
    paths-ignore:
      - '**.yml'
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.yml'
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 12
          - 14
          - 15.0.1
          - 15
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx panva/npm-install-retry
      - run: npm run coverage
